jackpot_results_glm <- glm(
# RaceHorse.Time
RaceHorse.IsHitA
# RaceHorse.TimeDv
# RaceHorse.TimeDvByRace
# RaceHorse.TimeDvByJyoType1
# RaceHorse.TimeDvByRaceType0
# RaceHorse.TimeDvByRaceType1
# RaceHorse.LastTimeDv
# RaceHorse.LastTimeDvByRace
# RaceHorse.LastTimeDvByJyoType1
# RaceHorse.LastTimeDvByRaceType0
# RaceHorse.LastTimeDvByRaceType1
# RaceHorse.LastSpeedDvByRace
# RaceHorse.LastSpeedDvByJyoType1
# RaceHorse.LastSpeedDvByRaceType0
# RaceHorse.LastSpeedDvByRaceType1
# RaceHorse.LastTimeSpeedDvByRace
# RaceHorse.LastTimeSpeedDvByJyoType1
# RaceHorse.LastTimeSpeedDvByRaceType0
# RaceHorse.LastTimeSpeedDvByRaceType1
~
+ 1
# + Race.RecKubun
# + Race.DataKubun
# + Race.MakeDate
# + Race.RaceDate
# + Race.JyoCd
# + Race.Kaiji
# + Race.Nichiji
# + Race.RaceNum
# + Race.RaceId
# + Race.YoubiCd
# + Race.TokuNum
# + Race.Hondai
# + Race.Fukudai
# + Race.Kakko
# + Race.HondaiEng
# + Race.FukudaiEng
# + Race.KakkoEng
# + Race.Ryakusyo10
# + Race.Ryakusyo6
# + Race.Ryakusyo3
# + Race.Kubun
# + Race.Nkai
# + Race.GradeCd
# + Race.GradeCdBefore
# + Race.SyubetuCd
# + Race.KigoCd
# + Race.JyuryoCd
# + Race.Jyoken1Cd
# + Race.Jyoken2Cd
# + Race.Jyoken3Cd
# + Race.Jyoken4Cd
# + Race.Jyoken5Cd
# + Race.JyokenName
# + Race.Kyori
# + Race.KyoriBefore
# + Race.DistanceTypeCd
# + Race.DistanceType2Cd
# + Race.TrackCd
# + Race.TrackCdBefore
# + Race.CourseKubunCd
# + Race.CourseKubunCdBefore
# + Race.Honsyokin1
# + Race.Honsyokin2
# + Race.Honsyokin3
# + Race.Honsyokin4
# + Race.Honsyokin5
# + Race.Honsyokin6
# + Race.Honsyokin7
# + Race.HonsyokinBefore1
# + Race.HonsyokinBefore2
# + Race.HonsyokinBefore3
# + Race.HonsyokinBefore4
# + Race.HonsyokinBefore5
# + Race.Fukasyokin1
# + Race.Fukasyokin2
# + Race.Fukasyokin3
# + Race.Fukasyokin4
# + Race.Fukasyokin5
# + Race.FukasyokinBefore1
# + Race.FukasyokinBefore2
# + Race.FukasyokinBefore3
# + Race.HassoTime
# + Race.HassoTimeBefore
# + Race.TorokuTosu
# + Race.SyussoTosu
# + Race.NyusenTosu
# + Race.TenkoCd
# + Race.TrackTypeCd
# + Race.TrackType2Cd
# + Race.TrackType3Cd
# + Race.CourseTypeCd
# + Race.TrackConditionCd
# + Race.SibaBabaCd
# + Race.DirtBabaCd
# + Race.FastestStart3Time
# + Race.FastestStart8Time
# + Race.FastestStart4Time
# + Race.FastestLast3Time
# + Race.FastestLast4Time
# + Race.RecordUpKubun
# + Race.IsUpdatedEntity
# + Race.Timestamp01
# + Race.IsJraRace
# + Race.IsUpdatedRace
# + Race.IsUpdatedRaceHorse
# + Race.IsUpdatedDataMining
# + Race.IsUpdatedDataMiningTaisen
# + Race.IsUpdatedRaceHorseHistory
# + Race.IsPredictedRace
# + Race.Timestamp02
# + Race.IsConfirmedRace
# + Race.IsAnalyzeNormalPastAndFuture
# + Race.IsAnalyzeNormalPast
# + Race.IsAnalyzeNormalFuture
# + Race.IsAnalyzeFullPastAndFuture
# + Race.IsAnalyzeFullPast
# + Race.IsAnalyzeFullFuture
# + Race.JyokenCd
# + Race.JyoType1Cd
# + Race.RaceType0Cd
# + Race.RaceType1Cd
# + Race.RaceType2Cd
# + Race.RaceType3Cd
# + Race.RaceType4Cd
# + Race.ThisRaceYear
# + Race.PrevRaceYear
# + Race.AnalyzeGeneralRaceDateFrom
# + Race.AnalyzeGeneralRaceDateTo
# + Race.AnalyzeGen01RaceDateFrom
# + Race.AnalyzeGen01RaceDateTo
# + Race.AnalyzeGen01RaceDateFrom
# + Race.AnalyzeGen01RaceDateTo
# + Race.AnalyzeHorseRaceDateFrom
# + Race.AnalyzeHorseRaceDateTo
# + Race.AnalyzeJockyRaceDateFrom
# + Race.AnalyzeJockyRaceDateTo
# + Race.KyoriRemainder
# + Race.FastestStart38Time
# + Race.Timestamp03
# + Race.CrawlDatetime
# + Race.IsAutoBet
# + Race.AutoBetDatetime
# + Race.Timestamp05
# + Race.Guid
# + Race.DefaultHitRateA
# + Race.DefaultHitRateB
# + Race.DefaultHitRateC
# + RaceHorse.RecKubun
# + RaceHorse.DataKubun
# + RaceHorse.MakeDate
# + RaceHorse.RaceDate
# + RaceHorse.JyoCd
# + RaceHorse.Kaiji
# + RaceHorse.Nichiji
# + RaceHorse.RaceNum
# + RaceHorse.RaceId
# + RaceHorse.KettoNum
# + RaceHorse.Wakuban
# + RaceHorse.Umaban
# + RaceHorse.Bamei
# + RaceHorse.UmaKigoCd
# + RaceHorse.SexCd
# + RaceHorse.IsSex1
# + RaceHorse.IsSex2
# + RaceHorse.IsSex3
# + RaceHorse.HinsyuCd
# + RaceHorse.KeiroCd
# + RaceHorse.Barei
# + RaceHorse.TozaiCd
# + RaceHorse.ChokyosiCode
# + RaceHorse.ChokyosiRyakusyo
# + RaceHorse.BanusiCode
# + RaceHorse.BanusiName
# + RaceHorse.ColourCd
# + RaceHorse.Reserved1
# + RaceHorse.Futan
# + RaceHorse.FutanBefore
# + RaceHorse.BlinkerCd
# + RaceHorse.IsBlinker
# + RaceHorse.Reserved2
# + RaceHorse.KisyuCode
# + RaceHorse.KisyuCodeBefore
# + RaceHorse.KisyuRyakusyo
# + RaceHorse.KisyuRyakusyoBefore
# + RaceHorse.MinaraiCd
# + RaceHorse.IsMinarai0
# + RaceHorse.IsMinarai1
# + RaceHorse.IsMinarai2
# + RaceHorse.IsMinarai3
# + RaceHorse.IsMinarai4
# + RaceHorse.IsMinarai9
# + RaceHorse.MinaraiCdBefore
# + RaceHorse.Bataijyu
# + RaceHorse.ZogenFugo
# + RaceHorse.ZogenSa
# + RaceHorse.IjyoCd
# + RaceHorse.NyusenJyuni
# + RaceHorse.KakuteiJyuni
# + RaceHorse.DochakuKubun
# + RaceHorse.DochakuTosu
# + RaceHorse.Time
# + RaceHorse.ChakusaCd
# + RaceHorse.ChakusaCdP
# + RaceHorse.ChakusaCdPp
# + RaceHorse.Jyuni1C
# + RaceHorse.Jyuni2C
# + RaceHorse.Jyuni3C
# + RaceHorse.Jyuni4C
# + RaceHorse.Odds
# + RaceHorse.Ninki
# + RaceHorse.Honsyokin
# + RaceHorse.Fukasyokin
# + RaceHorse.Reserved3
# + RaceHorse.Reserved4
# + RaceHorse.Last4Time
# + RaceHorse.Last3Time
# + RaceHorse.KettoNum1
# + RaceHorse.Bamei1
# + RaceHorse.KettoNum2
# + RaceHorse.Bamei2
# + RaceHorse.KettoNum3
# + RaceHorse.Bamei3
# + RaceHorse.TimeDiff
# + RaceHorse.RecordUpKubun
# + RaceHorse.DmKubun
# + RaceHorse.DmTime
# + RaceHorse.DmGosaP
# + RaceHorse.DmGosaM
# + RaceHorse.DmJyuni
# + RaceHorse.RunTypeCd
# + RaceHorse.RunType
# + RaceHorse.IsRunType1
# + RaceHorse.IsRunType2
# + RaceHorse.IsRunType3
# + RaceHorse.IsRunType4
# + RaceHorse.IsUpdatedEntity
# + RaceHorse.IsConfirmedRaceHorse
# + RaceHorse.RunNum
# + RaceHorse.RunNumDesc
# + RaceHorse.IsRun
# + RaceHorse.Lifetime
# + RaceHorse.FutanRatio
# + RaceHorse.IsHit1
# + RaceHorse.IsHit2
# + RaceHorse.IsHit3
# + RaceHorse.IsHit4
# + RaceHorse.IsHit5
# + RaceHorse.IsHit6
# + RaceHorse.PrevRaceId
# + RaceHorse.PrevRunNum
# + RaceHorse.PrevJyokenCd
# + RaceHorse.PrevJyoType1Cd
# + RaceHorse.PrevRaceType0Cd
# + RaceHorse.PrevRaceType1Cd
# + RaceHorse.PrevRaceType2Cd
# + RaceHorse.PrevRaceType3Cd
# + RaceHorse.PrevRaceType4Cd
# + RaceHorse.IsValidPrepTimeSdv
# + RaceHorse.PrepTimeSdv
# + RaceHorse.PrepTimeDv
# + RaceHorse.IsValidRaceHorse
# + RaceHorse.Speed
# + RaceHorse.LastSpeed
# + RaceHorse.IsValidTimeSdv
# + RaceHorse.TimeSdv
# + RaceHorse.TimeDv
# + RaceHorse.TimeRank
# + RaceHorse.IsValidTimeSdvByRace
# + RaceHorse.TimeSdvByRace
# + RaceHorse.TimeDvByRace
# + RaceHorse.TimeRankByRace
# + RaceHorse.IsValidTimeSdvByJyoType1
# + RaceHorse.TimeSdvByJyoType1
# + RaceHorse.TimeDvByJyoType1
# + RaceHorse.TimeRankByJyoType1
# + RaceHorse.IsValidTimeSdvByRaceType0
# + RaceHorse.TimeSdvByRaceType0
# + RaceHorse.TimeDvByRaceType0
# + RaceHorse.TimeRankByRaceType0
# + RaceHorse.IsValidTimeSdvByRaceType1
# + RaceHorse.TimeSdvByRaceType1
# + RaceHorse.TimeDvByRaceType1
# + RaceHorse.TimeRankByRaceType1
# + RaceHorse.IsValidLastTimeSdv
# + RaceHorse.LastTimeSdv
# + RaceHorse.LastTimeDv
# + RaceHorse.LastTimeRank
# + RaceHorse.IsValidLastTimeSdvByRace
# + RaceHorse.LastTimeSdvByRace
# + RaceHorse.LastTimeDvByRace
# + RaceHorse.LastTimeRankByRace
# + RaceHorse.IsValidLastTimeSdvByJyoType1
# + RaceHorse.LastTimeSdvByJyoType1
# + RaceHorse.LastTimeDvByJyoType1
# + RaceHorse.LastTimeRankByJyoType1
# + RaceHorse.IsValidLastTimeSdvByRaceType0
# + RaceHorse.LastTimeSdvByRaceType0
# + RaceHorse.LastTimeDvByRaceType0
# + RaceHorse.LastTimeRankByRaceType0
# + RaceHorse.IsValidLastTimeSdvByRaceType1
# + RaceHorse.LastTimeSdvByRaceType1
# + RaceHorse.LastTimeDvByRaceType1
# + RaceHorse.LastTimeRankByRaceType1
# + RaceHorse.IsValidBareiSdv
# + RaceHorse.BareiSdv
# + RaceHorse.BareiDv
# + RaceHorse.IsValidBataijyuSdv
# + RaceHorse.BataijyuSdv
# + RaceHorse.BataijyuDv
# + RaceHorse.IsValidFutanSdv
# + RaceHorse.FutanSdv
# + RaceHorse.FutanDv
# + RaceHorse.IsValidLifetimeSdv
# + RaceHorse.LifetimeSdv
# + RaceHorse.LifetimeDv
# + RaceHorse.IsValidFutanRatioSdv
# + RaceHorse.FutanRatioSdv
# + RaceHorse.FutanRatioDv
# + RaceHorse.IsValidSpeedSdv
# + RaceHorse.SpeedSdv
# + RaceHorse.SpeedDv
# + RaceHorse.IsValidSpeedSdvByRace
# + RaceHorse.SpeedSdvByRace
# + RaceHorse.SpeedDvByRace
# + RaceHorse.IsValidSpeedSdvByJyoType1
# + RaceHorse.SpeedSdvByJyoType1
# + RaceHorse.SpeedDvByJyoType1
# + RaceHorse.IsValidSpeedSdvByRaceType0
# + RaceHorse.SpeedSdvByRaceType0
# + RaceHorse.SpeedDvByRaceType0
# + RaceHorse.IsValidSpeedSdvByRaceType1
# + RaceHorse.SpeedSdvByRaceType1
# + RaceHorse.SpeedDvByRaceType1
# + RaceHorse.IsValidLastSpeedSdv
# + RaceHorse.LastSpeedSdv
# + RaceHorse.LastSpeedDv
# + RaceHorse.IsValidLastSpeedSdvByRace
# + RaceHorse.LastSpeedSdvByRace
# + RaceHorse.LastSpeedDvByRace
# + RaceHorse.IsValidLastSpeedSdvByJyoType1
# + RaceHorse.LastSpeedSdvByJyoType1
# + RaceHorse.LastSpeedDvByJyoType1
# + RaceHorse.IsValidLastSpeedSdvByRaceType0
# + RaceHorse.LastSpeedSdvByRaceType0
# + RaceHorse.LastSpeedDvByRaceType0
# + RaceHorse.IsValidLastSpeedSdvByRaceType1
# + RaceHorse.LastSpeedSdvByRaceType1
# + RaceHorse.LastSpeedDvByRaceType1
# + RaceHorse.StdTimeByClass
# + RaceHorse.StdTime
# + RaceHorse.StdJyoType1Cd
# + RaceHorse.StdRaceType1Cd
# + RaceHorse.StdFutan
# + RaceHorse.StdPrevJyoType1Cd
# + RaceHorse.StdPrevRaceType1Cd
# + RaceHorse.StdPrevFutan
# + RaceHorse.IsValidStdTimeSdv
# + RaceHorse.StdTimeSdv
# + RaceHorse.StdTimeDv
# + RaceHorse.StdTimeRank
# + RaceHorse.StdTimeSdvByRace
# + RaceHorse.StdTimeDvByRace
# + RaceHorse.StdTimeRankByRace
# + RaceHorse.IsValidPredictTime
# + RaceHorse.PredictTime
# + RaceHorse.PredictTimeSdvByRace
# + RaceHorse.PredictTimeDvByRace
# + RaceHorse.PredictTimeRankByRace
# + RaceHorse.IsValidPerfTime
# + RaceHorse.PerfTime
# + RaceHorse.PerfTimeSdvByRace
# + RaceHorse.PerfTimeDvByRace
# + RaceHorse.PerfTimeRankByRace
# + RaceHorse.PredictDatetime
# + RaceHorse.IsValidPredictValueA
# + RaceHorse.PredictValueA
# + RaceHorse.PredictValueDvA
# + RaceHorse.PredictValueRankA
# + RaceHorse.PredictErrorA
# + RaceHorse.ExpectedOddsA
# + RaceHorse.Odds1A
# + RaceHorse.Odds2A
# + RaceHorse.IsValidPredictValueB
# + RaceHorse.PredictValueB
# + RaceHorse.PredictValueDvB
# + RaceHorse.PredictValueRankB
# + RaceHorse.PredictErrorB
# + RaceHorse.ExpectedOddsB
# + RaceHorse.Odds1B
# + RaceHorse.Odds2B
# + RaceHorse.IsValidPredictValueC
# + RaceHorse.PredictValueC
# + RaceHorse.PredictValueDvC
# + RaceHorse.PredictValueRankC
# + RaceHorse.PredictErrorC
# + RaceHorse.ExpectedOddsC
# + RaceHorse.Odds1C
# + RaceHorse.Odds2C
# + RaceHorse.OddsLog
# + RaceHorse.OddsRatio
# + RaceHorse.OddsLogit
# + RaceHorse.ApprovalRate
# + RaceHorse.ApprovalRateLog
# + RaceHorse.IsHitA
# + RaceHorse.IsHitB
# + RaceHorse.IsHitC
# + RaceHorse.IsHitD
# + RaceHorse.IsHitE
# + RaceHorse.LifetimeLog

# + Gen01.RaceId
# + Gen01.KettoNum
# + Gen01.HansyokuNum
# + Gen01.PrevRaceId
# + Gen01.PrevKettoNum
# + Gen01.PrevJyoType1Cd
# + Gen01.PrevRaceType1Cd
# + Gen01.IsRun
# + Gen01.IsHitA
# + Gen01.IsHitB
# + Gen01.IsHitC
+ Gen01.TimeDvByRace
+ Gen01.LastTimeDvByRace
# + Gen01.SpeedDvByRace
# + Gen01.LastSpeedDvByRace
# + EOF

# offset = log(PrevH01RaceHorse.TotalRunCount + 1)

# ,family = "gaussian"
,family = "binomial"
# ,family = "gaussian"
# ,family = "poisson"
# ,method = "REML"
# ,method = "ML"
# ,method = "Laplace"
# ,method = "AGQ" 	#Not Implement
,data=data
# ,data = subset(data6, Race.IsAnalyzeNormalPast == 1)
)
