print(paste0(Sys.time(),  " --- source_transform.R Start ---"))

#-------------------------------------
#Transform
#-------------------------------------
# as.POSIXct("2020-05-01",tz="UTC")
# as.POSIXit("2020-05-01",tz="UTC")
data<-transform(data
# InputDataSet<-transform(InputDataSet

# ,Race.JyoCd=as.factor(as.integer(Race.JyoCd))
# ,Race.GradeCd=as.factor(Race.GradeCd)
# ,Race.SyubetuCd=as.factor(Race.SyubetuCd)
# ,Race.KigoCd=as.factor(Race.KigoCd)
# ,Race.JyuryoCd=as.factor(Race.JyuryoCd)
# ,Race.DistanceTypeCd=as.factor(Race.DistanceTypeCd)
# ,Race.DistanceType2Cd=as.factor(Race.DistanceType2Cd)
# ,Race.TrackCd=as.factor(Race.TrackCd)
# ,Race.CourseKubunCd=as.factor(Race.CourseKubunCd)
# ,Race.HassoTime=as.POSIXct(Race.HassoTime)
# ,Race.TenkoCd=as.factor(Race.TenkoCd)
# ,Race.TrackTypeCd=as.factor(Race.TrackTypeCd)
# ,Race.CourseTypeCd=as.factor(Race.CourseTypeCd)
# ,Race.TrackConditionCd=as.factor(Race.TrackConditionCd)
,Race.JyokenCd=as.factor(Race.JyokenCd)
,Race.JyoType1Cd=as.factor(Race.JyoType1Cd)
,Race.RaceType0Cd=as.factor(Race.RaceType0Cd)
,Race.RaceType1Cd=as.factor(Race.RaceType1Cd)
# ,Race.RaceType2Cd=as.factor(Race.RaceType2Cd)
# ,Race.RaceType3Cd=as.factor(Race.RaceType3Cd)
# ,Race.RaceType4Cd=as.factor(Race.RaceType4Cd)
 
# ,RaceHorse.RaceDate=as.POSIXct(RaceHorse.RaceDate)
# ,RaceHorse.RaceId=as.factor(RaceHorse.RaceId)
# ,RaceHorse.KettoNum=as.factor(RaceHorse.KettoNum)
# ,RaceHorse.UmaKigoCd=as.factor(RaceHorse.UmaKigoCd)
# ,RaceHorse.SexCd=as.factor(RaceHorse.SexCd)
# ,RaceHorse.HinsyuCd=as.factor(RaceHorse.HinsyuCd)
# ,RaceHorse.KeiroCd=as.factor(as.integer(RaceHorse.KeiroCd))
# ,RaceHorse.TozaiCd=as.factor(RaceHorse.TozaiCd)
# ,RaceHorse.ChokyosiCode=as.factor(RaceHorse.ChokyosiCode)
# ,RaceHorse.BanusiCode=as.factor(RaceHorse.BanusiCode)
# ,RaceHorse.BlinkerCd=as.factor(RaceHorse.BlinkerCd)
# ,RaceHorse.KisyuCode=as.factor(RaceHorse.KisyuCode)
# ,RaceHorse.MinaraiCd=as.factor(as.character(RaceHorse.MinaraiCd))
# ,RaceHorse.RunTypeCd=as.factor(RaceHorse.RunTypeCd)

# ,PrevRace.JyoCd=as.factor(as.integer(PrevRace.JyoCd))
# ,PrevRace.GradeCd=as.factor(PrevRace.GradeCd)
# ,PrevRace.SyubetuCd=as.factor(PrevRace.SyubetuCd)
# ,PrevRace.KigoCd=as.factor(PrevRace.KigoCd)
# ,PrevRace.JyuryoCd=as.factor(PrevRace.JyuryoCd)
# ,PrevRace.DistanceTypeCd=as.factor(PrevRace.DistanceTypeCd)
# ,PrevRace.DistanceType2Cd=as.factor(PrevRace.DistanceType2Cd)
# ,PrevRace.TrackCd=as.factor(PrevRace.TrackCd)
# ,PrevRace.CourseKubunCd=as.factor(PrevRace.CourseKubunCd)
# ,PrevRace.HassoTime=as.POSIXct(PrevRace.HassoTime)
# ,PrevRace.TenkoCd=as.factor(PrevRace.TenkoCd)
# ,PrevRace.TrackTypeCd=as.factor(PrevRace.TrackTypeCd)
# ,PrevRace.CourseTypeCd=as.factor(PrevRace.CourseTypeCd)
# ,PrevRace.TrackConditionCd=as.factor(PrevRace.TrackConditionCd)
# ,PrevRace.JyokenCd=as.factor(PrevRace.JyokenCd)
# ,PrevRace.JyoType1Cd=as.factor(PrevRace.JyoType1Cd)
# ,PrevRace.RaceType0Cd=as.factor(PrevRace.RaceType0Cd)
# ,PrevRace.RaceType1Cd=as.factor(PrevRace.RaceType1Cd)
# ,PrevRace.RaceType2Cd=as.factor(PrevRace.RaceType2Cd)
# ,PrevRace.RaceType3Cd=as.factor(PrevRace.RaceType3Cd)
# ,PrevRace.RaceType4Cd=as.factor(PrevRace.RaceType4Cd)

# ,PrevRaceHorse.RaceDate=as.POSIXct(PrevRaceHorse.RaceDate)
# ,PrevRaceHorse.RaceId=as.factor(PrevRaceHorse.RaceId)
# ,PrevRaceHorse.KettoNum=as.factor(PrevRaceHorse.KettoNum)
# ,PrevRaceHorse.UmaKigoCd=as.factor(PrevRaceHorse.UmaKigoCd)
# ,PrevRaceHorse.SexCd=as.factor(PrevRaceHorse.SexCd)
# ,PrevRaceHorse.HinsyuCd=as.factor(PrevRaceHorse.HinsyuCd)
# ,PrevRaceHorse.KeiroCd=as.factor(as.integer(PrevRaceHorse.KeiroCd))
# ,PrevRaceHorse.TozaiCd=as.factor(PrevRaceHorse.TozaiCd)
# ,PrevRaceHorse.ChokyosiCode=as.factor(PrevRaceHorse.ChokyosiCode)
# ,PrevRaceHorse.BanusiCode=as.factor(PrevRaceHorse.BanusiCode)
# ,PrevRaceHorse.BlinkerCd=as.factor(PrevRaceHorse.BlinkerCd)
# ,PrevRaceHorse.KisyuCode=as.factor(PrevRaceHorse.KisyuCode)
# ,PrevRaceHorse.MinaraiCd=as.factor(as.character(PrevRaceHorse.MinaraiCd))
# ,PrevRaceHorse.RunTypeCd=as.factor(PrevRaceHorse.RunTypeCd)

# ,OddsByWin.Odds1=as.numeric(OddsByWin.Odds1)
# ,OddsByWin.Ninki=as.integer(OddsByWin.Ninki)
# ,OddsByWin.OddsLog1=as.numeric(OddsByWin.OddsLog1)
# ,OddsByWin.OddsRatio1=as.numeric(OddsByWin.OddsRatio1)
# ,OddsByWin.OddsLogit1=as.numeric(OddsByWin.OddsLogit1)
# ,OddsByWin.ApprovalRate1=as.numeric(OddsByWin.ApprovalRate1)
# ,OddsByWin.ApprovalRateLog1=as.numeric(OddsByWin.ApprovalRateLog1)

# , Horse.TimeDvByRace=as.numeric(Horse.TimeDvByRace)
# , Horse.TimeDvByRaceType1=as.numeric(Horse.TimeDvByRaceType1)
# , Horse.RunCount=as.integer(Horse.RunCount)
# , Horse.HitCount1=as.integer(Horse.HitCount1)
# , Horse.HitCount2=as.integer(Horse.HitCount2)
# , Horse.HitCount3=as.integer(Horse.HitCount3)
# , Horse.HitCount4=as.integer(Horse.HitCount4)
# , Horse.HitCount5=as.integer(Horse.HitCount5)
# , Horse.HitCountA=as.integer(Horse.HitCountA)
# , Horse.HitCountB=as.integer(Horse.HitCountB)
# , Horse.HitCountC=as.integer(Horse.HitCountC)
# , Horse.HitRate1=as.numeric(Horse.HitRate1)
# , Horse.HitRate2=as.numeric(Horse.HitRate2)
# , Horse.HitRate3=as.numeric(Horse.HitRate3)
# , Horse.HitRate4=as.numeric(Horse.HitRate4)
# , Horse.HitRate5=as.numeric(Horse.HitRate5)
# , Horse.HitRateA=as.numeric(Horse.HitRateA)
# , Horse.HitRateB=as.numeric(Horse.HitRateB)
# , Horse.HitRateC=as.numeric(Horse.HitRateC)

# , Gen01.TimeDvByRace=as.numeric(Gen01.TimeDvByRace)
# , Gen01.TimeDvByRaceType1=as.numeric(Gen01.TimeDvByRaceType1)
# , Gen01.RunCount=as.integer(Gen01.RunCount)
# , Gen01.HitCount1=as.integer(Gen01.HitCount1)
# , Gen01.HitCount2=as.integer(Gen01.HitCount2)
# , Gen01.HitCount3=as.integer(Gen01.HitCount3)
# , Gen01.HitCount4=as.integer(Gen01.HitCount4)
# , Gen01.HitCount5=as.integer(Gen01.HitCount5)
# , Gen01.HitCountA=as.integer(Gen01.HitCountA)
# , Gen01.HitCountB=as.integer(Gen01.HitCountB)
# , Gen01.HitCountC=as.integer(Gen01.HitCountC)
# , Gen01.HitRate1=as.numeric(Gen01.HitRate1)
# , Gen01.HitRate2=as.numeric(Gen01.HitRate2)
# , Gen01.HitRate3=as.numeric(Gen01.HitRate3)
# , Gen01.HitRate4=as.numeric(Gen01.HitRate4)
# , Gen01.HitRate5=as.numeric(Gen01.HitRate5)
# , Gen01.HitRateA=as.numeric(Gen01.HitRateA)
# , Gen01.HitRateB=as.numeric(Gen01.HitRateB)
# , Gen01.HitRateC=as.numeric(Gen01.HitRateC)

# , Gen02.TimeDvByRace=as.numeric(Gen02.TimeDvByRace)
# , Gen02.TimeDvByRaceType1=as.numeric(Gen02.TimeDvByRaceType1)
# , Gen02.RunCount=as.integer(Gen02.RunCount)
# , Gen02.HitCount1=as.integer(Gen02.HitCount1)
# , Gen02.HitCount2=as.integer(Gen02.HitCount2)
# , Gen02.HitCount3=as.integer(Gen02.HitCount3)
# , Gen02.HitCount4=as.integer(Gen02.HitCount4)
# , Gen02.HitCount5=as.integer(Gen02.HitCount5)
# , Gen02.HitCountA=as.integer(Gen02.HitCountA)
# , Gen02.HitCountB=as.integer(Gen02.HitCountB)
# , Gen02.HitCountC=as.integer(Gen02.HitCountC)
# , Gen02.HitRate1=as.numeric(Gen02.HitRate1)
# , Gen02.HitRate2=as.numeric(Gen02.HitRate2)
# , Gen02.HitRate3=as.numeric(Gen02.HitRate3)
# , Gen02.HitRate4=as.numeric(Gen02.HitRate4)
# , Gen02.HitRate5=as.numeric(Gen02.HitRate5)
# , Gen02.HitRateA=as.numeric(Gen02.HitRateA)
# , Gen02.HitRateB=as.numeric(Gen02.HitRateB)
# , Gen02.HitRateC=as.numeric(Gen02.HitRateC)

)

print(paste0(Sys.time(),  " --- source_transform.R Finished ---"))
